### PR TITLE
Microverse portifolio page

### PR DESCRIPTION
**Pull request by LDouglasOT**
**Tasks Completed**

- Added linters to the project
- Fixed Lighthouse CLI
- Built the UI for the page

### CODE REVIEW

**Review by Felix45 — CHANGES_REQUESTED** [review]
Hi @LDouglasOT , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that 
- [x] Has implemented multiple features in a single pull request, please note that for each milestone in a project you need to create a `new feature branch` and open a `new pull request` from that feature branch. Please don't implement all the project milestones in one `feature branch`

- [x] Has no professional readme file, please use this [readme template](https://github.com/microverseinc/readme-template) from Microverse to update your readme file. A professional readme serves to inform people viewing your repository what your project is about. kindly implement these changes and ask for a new review.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by frank1738 — COMMENTED** [review]
- [x] You updated your readme file after submitting or while submitting your project

**Comment by LDouglasOT** [comment]
Hey, @frank1738 I updated it after submiting it, I had forgotten about it. Sorry for any inconveniences caused please.

Thanks.

**Review by frank1738 — APPROVED** [review]
Hi @LDouglasOT , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

YesYouAreGIF (2)


## Highlights

✅ No linter error
✅ README is okay
✅Good Design 👍 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
